import Link from 'next/link';
import { WEB_SHOWCASE } from '@/content/service-showcase';
import BrumaDemo from '@/components/showcase/BrumaDemo';
import type { Locale } from '@/content/servicios';

const copy = {
  es: {
    example: 'Del mensaje a la experiencia', concept: 'Bruma · ejemplo ilustrativo, no un cliente real', caption: 'Una propuesta clara, una carta fácil de recorrer y un siguiente paso visible. El diseño se adapta a tu identidad; no incluye reservas ni tienda.', open: 'Explorar el ejemplo', scope: 'La demo ilustra una landing. Blog, integraciones y páginas adicionales dependen del paquete y los extras elegidos.', benefits: 'Que tu visita sepa qué hacer después', outcomes: [['Explicá tu propuesta', 'Una página ordenada ayuda a entender qué ofrecés y para quién.'], ['Facilitá la consulta', 'Un camino de contacto visible evita que la visita tenga que buscar el siguiente paso.'], ['Presentate en cualquier pantalla', 'Contenido y navegación adaptables a móvil y escritorio.']], process: 'De tu idea a una web propia', steps: [['Acordamos el alcance', 'Elegís paquete, respondés las preguntas y aportás los materiales requeridos.'], ['Construimos y revisamos', 'El trabajo comienza al cumplir las condiciones del pedido. Revisamos dentro del alcance acordado.'], ['Entregamos y transferimos', 'Recibís los entregables. Hosting inicial y garantía: 30 días; luego cuidado aceptado o transferencia acordada.']], faq: 'Antes de decidir', questions: [['¿La web será igual al ejemplo?', 'No. Bruma muestra una dirección visual, no una plantilla obligatoria. La identidad y el contenido se adaptan al alcance contratado.'], ['¿Qué necesito entregar?', 'Textos, identidad y materiales según el paquete. Tu pedido conserva los requisitos acordados y el plazo parte de sus condiciones de inicio.'], ['¿Incluye hosting para siempre?', 'No. El hosting inicial y la garantía por defectos cubren 30 días. La continuidad paga requiere aceptación expresa y fecha acordada, o una transferencia planificada. El dominio y los terceros se pagan por separado.'], ['¿Qué estoy contratando?', 'El paquete y los extras seleccionados, no todas las posibilidades del ejemplo. Podés leer el alcance completo y los costos antes de preparar el contrato.']], close: 'Tu próximo paso, sin adivinar el alcance.', packages: 'Ver paquetes y precios', consult: 'Consultar un alcance diferente',
  },
  en: {
    example: 'From message to experience', concept: 'Bruma · illustrative example, not a real customer', caption: 'A clear offer, an easy-to-browse menu and a visible next step. The design adapts to your identity; bookings and a store are not included.', open: 'Explore the example', scope: 'The demo illustrates a landing page. Blog, integrations and additional pages depend on your selected package and extras.', benefits: 'Help visitors understand their next step', outcomes: [['Explain your offer', 'An organized page helps visitors understand what you offer and who it is for.'], ['Make inquiries easier', 'A visible contact path keeps visitors from searching for the next step.'], ['Show up on every screen', 'Content and navigation adapt to mobile and desktop.']], process: 'From your idea to your own website', steps: [['Agree the scope', 'Choose a package, answer the questions and provide the required materials.'], ['Build and review', 'Work begins once the order prerequisites are met. Review stays within the agreed scope.'], ['Deliver and hand over', 'Receive your deliverables. Initial hosting and warranty: 30 days; then explicitly accepted care or an agreed transfer.']], faq: 'Before you decide', questions: [['Will my website look exactly like the example?', 'No. Bruma demonstrates a visual direction, not a required template. Identity and content adapt to the agreed scope.'], ['What do I need to provide?', 'Copy, identity and materials appropriate to the package. Your order retains the agreed requirements; delivery timing depends on its start conditions.'], ['Is hosting included forever?', 'No. Initial hosting and defect warranty cover 30 days. Paid continuation needs explicit acceptance and an agreed start date, or a planned transfer. Domain and third-party costs are separate.'], ['What am I buying?', 'Your selected package and extras, not every design possibility in the example. Read the full scope and costs before preparing the contract.']], close: 'Your next step, with the scope clear.', packages: 'See packages and prices', consult: 'Discuss a different scope',
  },
} as const;

export function WebMarketingIntro({ locale }: { locale: Locale }) {
  const t = copy[locale];
  return <div className="site-container space-y-16 py-12 sm:py-16">
    <section id="example" aria-labelledby="web-example-title" className="scroll-mt-40">
      <div className="mb-7 grid gap-5 lg:grid-cols-[1fr_1fr]"><div><p className="technical-label">{t.concept}</p><h2 id="web-example-title" className="mt-3 text-3xl font-medium tracking-tight sm:text-4xl">{t.example}</h2></div><p className="text-base leading-7 text-text-secondary">{t.caption}</p></div>
      <BrumaDemo locale={locale} preview />
      <div className="mt-5 flex flex-wrap items-start justify-between gap-5"><p className="max-w-2xl text-sm leading-6 text-text-secondary">{t.scope}</p><Link className="button-secondary" href={WEB_SHOWCASE.routes[locale]}>{t.open} ↗</Link></div>
    </section>
    <section aria-labelledby="web-benefits-title"><h2 id="web-benefits-title" className="text-3xl font-medium tracking-tight">{t.benefits}</h2><div className="mt-8 grid gap-8 md:grid-cols-3">{t.outcomes.map(([title, text], i) => <div key={title} className="border-t border-outline-ghost/20 pt-5"><p className="technical-label">0{i + 1}</p><h3 className="mt-3 text-xl font-medium">{title}</h3><p className="mt-3 text-base leading-7 text-text-secondary">{text}</p></div>)}</div></section>
    <section aria-labelledby="web-process-title"><h2 id="web-process-title" className="text-3xl font-medium tracking-tight">{t.process}</h2><ol className="mt-8 grid gap-8 md:grid-cols-3">{t.steps.map(([title, text], i) => <li key={title}><p className="technical-label">0{i + 1} / 03</p><h3 className="mt-3 text-xl font-medium">{title}</h3><p className="mt-3 text-base leading-7 text-text-secondary">{text}</p></li>)}</ol></section>
  </div>;
}

export function WebMarketingClose({ locale }: { locale: Locale }) {
  const t = copy[locale];
  return <div className="site-container space-y-16 pb-16"><section aria-labelledby="web-faq-title"><h2 id="web-faq-title" className="mb-6 text-3xl font-medium">{t.faq}</h2>{t.questions.map(([question, answer]) => <details key={question} className="border-t border-outline-ghost/20 py-5"><summary className="cursor-pointer text-base font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-brand-primary">{question}</summary><p className="mt-3 max-w-3xl text-base leading-7 text-text-secondary">{answer}</p></details>)}</section><section className="border-y border-outline-ghost/20 py-10"><h2 className="text-3xl font-medium">{t.close}</h2><div className="mt-6 flex flex-wrap gap-4"><a className="button-primary" href="#packages">{t.packages}</a><Link className="button-secondary" href={`/${locale}/services/agendar?service=web`}>{t.consult}</Link></div></section></div>;
}
