import { NextRequest, NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabase';
import { isAuthorized } from '@/lib/admin-auth';
import { sendCrmEmail } from '@/lib/resend';
import { questionnaireInviteHtml } from '@/lib/email-templates/questionnaire-invite';

export const dynamic = 'force-dynamic';

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  if (!isAuthorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { id } = await params;

    const { data: lead, error: leadError } = await getSupabaseAdmin()
      .from('leads')
      .select('nombre, email')
      .eq('id', id)
      .single();

    if (leadError || !lead) {
      return NextResponse.json({ error: 'Lead not found.' }, { status: 404 });
    }

    // Insert questionnaire row — token is auto-generated by the DB DEFAULT
    const { data: questionnaire, error: insertError } = await getSupabaseAdmin()
      .from('questionnaires')
      .insert({ lead_id: id })
      .select('id, token')
      .single();

    if (insertError) throw insertError;

    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://silvanopuccini.dev';
    const questionnaireUrl = `${siteUrl}/questionnaire/${questionnaire.token}`;

    await sendCrmEmail(
      lead.email,
      'Complete your project questionnaire',
      questionnaireInviteHtml({ name: lead.nombre, email: lead.email }, questionnaireUrl),
    );

    return NextResponse.json({ id: questionnaire.id }, { status: 201 });
  } catch (err) {
    console.error('[admin/leads/[id]/questionnaire] POST error:', err);
    return NextResponse.json({ error: 'Error sending questionnaire.' }, { status: 500 });
  }
}
